#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    Jul 11, 2019 08:37:57 AM KORST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import MWC_Lite_support
import os.path

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    root = tk.Tk()
    top = MWC (root)
    MWC_Lite_support.init(root, top)
    root.mainloop()

w = None
def create_MWC(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    rt = root
    w = tk.Toplevel (root)
    top = MWC (w)
    MWC_Lite_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_MWC():
    global w
    w.destroy()
    w = None

class MWC:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("1024x768+483+185")
        top.title("New Toplevel")
        top.configure(borderwidth="1")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.l_partBarcode = tk.Label(top)
        self.l_partBarcode.place(relx=0.039, rely=0.182, height=43, width=222)
        self.l_partBarcode.configure(activebackground="#f9f9f9")
        self.l_partBarcode.configure(activeforeground="black")
        self.l_partBarcode.configure(background="#d9d9d9")
        self.l_partBarcode.configure(disabledforeground="#a3a3a3")
        self.l_partBarcode.configure(font="-family {Segoe UI} -size 20 -weight bold")
        self.l_partBarcode.configure(foreground="#000000")
        self.l_partBarcode.configure(highlightbackground="#d9d9d9")
        self.l_partBarcode.configure(highlightcolor="black")
        self.l_partBarcode.configure(text='''PART BARCODE :''')

        self.l_weight = tk.Label(top)
        self.l_weight.place(relx=0.039, rely=0.326, height=43, width=126)
        self.l_weight.configure(activebackground="#f9f9f9")
        self.l_weight.configure(activeforeground="black")
        self.l_weight.configure(background="#d9d9d9")
        self.l_weight.configure(disabledforeground="#a3a3a3")
        self.l_weight.configure(font="-family {Segoe UI} -size 20 -weight bold")
        self.l_weight.configure(foreground="#000000")
        self.l_weight.configure(highlightbackground="#d9d9d9")
        self.l_weight.configure(highlightcolor="black")
        self.l_weight.configure(text='''WEIGHT :''')

        self.partBarcode = tk.Entry(top)
        self.partBarcode.place(relx=0.273, rely=0.169, height=70, relwidth=0.674)

        self.partBarcode.configure(background="white")
        self.partBarcode.configure(disabledforeground="#a3a3a3")
        self.partBarcode.configure(font="-family {Courier New} -size 20 -weight bold")
        self.partBarcode.configure(foreground="#000000")
        self.partBarcode.configure(highlightbackground="#d9d9d9")
        self.partBarcode.configure(highlightcolor="black")
        self.partBarcode.configure(insertbackground="black")
        self.partBarcode.configure(justify='center')
        self.partBarcode.configure(selectbackground="#c4c4c4")
        self.partBarcode.configure(selectforeground="black")

        self.weight = tk.Entry(top)
        self.weight.place(relx=0.273, rely=0.313,height=70, relwidth=0.674)
        self.weight.configure(background="white")
        self.weight.configure(disabledforeground="#a3a3a3")
        self.weight.configure(font="-family {Courier New} -size 20 -weight bold")
        self.weight.configure(foreground="#000000")
        self.weight.configure(highlightbackground="#d9d9d9")
        self.weight.configure(highlightcolor="black")
        self.weight.configure(insertbackground="black")
        self.weight.configure(justify='center')
        self.weight.configure(selectbackground="#c4c4c4")
        self.weight.configure(selectforeground="black")

        self.b_abort = tk.Button(top)
        self.b_abort.place(relx=0.557, rely=0.482, height=193, width=404)
        self.b_abort.configure(activebackground="#ececec")
        self.b_abort.configure(activeforeground="#000000")
        self.b_abort.configure(background="#d9d9d9")
        self.b_abort.configure(command=MWC_Lite_support.abortProcess)
        self.b_abort.configure(disabledforeground="#a3a3a3")
        self.b_abort.configure(font="-family {Segoe UI} -size 20 -weight bold")
        self.b_abort.configure(foreground="#000000")
        self.b_abort.configure(highlightbackground="#d9d9d9")
        self.b_abort.configure(highlightcolor="black")
        self.b_abort.configure(pady="0")
        self.b_abort.configure(text='''ABORT''')
        self.b_abort.configure(width=404)

        self.l_partNo = tk.Label(top)
        self.l_partNo.place(relx=0.039, rely=0.482, height=43, width=138)
        self.l_partNo.configure(activebackground="#f9f9f9")
        self.l_partNo.configure(activeforeground="black")
        self.l_partNo.configure(background="#d9d9d9")
        self.l_partNo.configure(disabledforeground="#a3a3a3")
        self.l_partNo.configure(font="-family {Segoe UI} -size 20 -weight bold")
        self.l_partNo.configure(foreground="#000000")
        self.l_partNo.configure(highlightbackground="#d9d9d9")
        self.l_partNo.configure(highlightcolor="black")
        self.l_partNo.configure(text='''PART NO :''')

        self.l_ALC = tk.Label(top)
        self.l_ALC.place(relx=0.039, rely=0.573, height=43, width=70)
        self.l_ALC.configure(activebackground="#f9f9f9")
        self.l_ALC.configure(activeforeground="black")
        self.l_ALC.configure(background="#d9d9d9")
        self.l_ALC.configure(disabledforeground="#a3a3a3")
        self.l_ALC.configure(font="-family {Segoe UI} -size 20 -weight bold")
        self.l_ALC.configure(foreground="#000000")
        self.l_ALC.configure(highlightbackground="#d9d9d9")
        self.l_ALC.configure(highlightcolor="black")
        self.l_ALC.configure(text='''ALC :''')

        self.partNo = tk.Entry(top)
        self.partNo.place(relx=0.186, rely=0.482,height=50, relwidth=0.307)
        self.partNo.configure(background="white")
        self.partNo.configure(disabledforeground="#a3a3a3")
        self.partNo.configure(font="-family {Courier New} -size 18 -weight bold")
        self.partNo.configure(foreground="#000000")
        self.partNo.configure(highlightbackground="#d9d9d9")
        self.partNo.configure(highlightcolor="black")
        self.partNo.configure(insertbackground="black")
        self.partNo.configure(justify='center')
        self.partNo.configure(selectbackground="#c4c4c4")
        self.partNo.configure(selectforeground="black")

        self.ALC = tk.Entry(top)
        self.ALC.place(relx=0.186, rely=0.573,height=50, relwidth=0.307)
        self.ALC.configure(background="white")
        self.ALC.configure(disabledforeground="#a3a3a3")
        self.ALC.configure(font="-family {Courier New} -size 18 -weight bold")
        self.ALC.configure(foreground="#000000")
        self.ALC.configure(highlightbackground="#d9d9d9")
        self.ALC.configure(highlightcolor="black")
        self.ALC.configure(insertbackground="black")
        self.ALC.configure(justify='center')
        self.ALC.configure(selectbackground="#c4c4c4")
        self.ALC.configure(selectforeground="black")

        self.l_readHistory = tk.Label(top)
        self.l_readHistory.place(relx=0.039, rely=0.664, height=43, width=114)
        self.l_readHistory.configure(activebackground="#f9f9f9")
        self.l_readHistory.configure(activeforeground="black")
        self.l_readHistory.configure(background="#d9d9d9")
        self.l_readHistory.configure(disabledforeground="#a3a3a3")
        self.l_readHistory.configure(font="-family {Segoe UI} -size 20 -weight bold")
        self.l_readHistory.configure(foreground="#000000")
        self.l_readHistory.configure(highlightbackground="#d9d9d9")
        self.l_readHistory.configure(highlightcolor="black")
        self.l_readHistory.configure(text='''MODEL :''')

        self.model = tk.Entry(top)
        self.model.place(relx=0.186, rely=0.664,height=50, relwidth=0.307)
        self.model.configure(background="white")
        self.model.configure(disabledforeground="#a3a3a3")
        self.model.configure(font="-family {Courier New} -size 18 -weight bold")
        self.model.configure(foreground="#000000")
        self.model.configure(highlightbackground="#d9d9d9")
        self.model.configure(highlightcolor="black")
        self.model.configure(insertbackground="black")
        self.model.configure(justify='center')
        self.model.configure(selectbackground="#c4c4c4")
        self.model.configure(selectforeground="black")

        self.topFrame = tk.Frame(top)
        self.topFrame.place(relx=0.0, rely=0.0, relheight=0.124, relwidth=1.0)
        self.topFrame.configure(relief='groove')
        self.topFrame.configure(borderwidth="1")
        self.topFrame.configure(relief="groove")
        self.topFrame.configure(background="#ffffff")
        self.topFrame.configure(highlightbackground="#d9d9d9")
        self.topFrame.configure(highlightcolor="black")
        self.topFrame.configure(width=1024)

        self.b_closeIt = tk.Button(self.topFrame)
        self.b_closeIt.place(relx=0.879, rely=0.105, height=65, width=75)
        self.b_closeIt.configure(activebackground="#ececec")
        self.b_closeIt.configure(activeforeground="#000000")
        self.b_closeIt.configure(background="#d9d9d9")
        self.b_closeIt.configure(command=MWC_Lite_support.closeIt)
        self.b_closeIt.configure(disabledforeground="#a3a3a3")
        self.b_closeIt.configure(font="-family {Segoe UI} -size 28 -weight bold")
        self.b_closeIt.configure(foreground="#000000")
        self.b_closeIt.configure(highlightbackground="#d9d9d9")
        self.b_closeIt.configure(highlightcolor="black")
        self.b_closeIt.configure(pady="0")
        self.b_closeIt.configure(text='''X''')

        self.logo = tk.Label(self.topFrame)
        self.logo.place(relx=0.049, rely=0.105, height=68, width=158)
        self.logo.configure(activebackground="#f9f9f9")
        self.logo.configure(activeforeground="black")
        self.logo.configure(background="#ffffff")
        self.logo.configure(disabledforeground="#a3a3a3")
        self.logo.configure(foreground="#000000")
        self.logo.configure(highlightbackground="#d9d9d9")
        self.logo.configure(highlightcolor="black")
        photo_location = os.path.join(prog_location,"../Weight Control/MobisWeightControl/Mobis.png")
        self._img0 = tk.PhotoImage(file=photo_location)
        self.logo.configure(image=self._img0)

        self.l_title = tk.Label(self.topFrame)
        self.l_title.place(relx=0.303, rely=0.211, height=51, width=424)
        self.l_title.configure(activebackground="#f9f9f9")
        self.l_title.configure(activeforeground="black")
        self.l_title.configure(background="#ffffff")
        self.l_title.configure(disabledforeground="#a3a3a3")
        self.l_title.configure(font="-family {Segoe UI} -size 23 -weight bold")
        self.l_title.configure(foreground="#000000")
        self.l_title.configure(highlightbackground="#d9d9d9")
        self.l_title.configure(highlightcolor="black")
        self.l_title.configure(text='''WEIGHT CONTROL STATION''')

        self.fra53_lab45 = tk.Label(self.topFrame)
        self.fra53_lab45.place(relx=0.718, rely=0.526, height=31, width=54)
        self.fra53_lab45.configure(activebackground="#f9f9f9")
        self.fra53_lab45.configure(activeforeground="black")
        self.fra53_lab45.configure(background="#ffffff")
        self.fra53_lab45.configure(disabledforeground="#a3a3a3")
        self.fra53_lab45.configure(font="-family {Segoe UI} -size 23 -slant italic")
        self.fra53_lab45.configure(foreground="#000000")
        self.fra53_lab45.configure(highlightbackground="#d9d9d9")
        self.fra53_lab45.configure(highlightcolor="black")
        self.fra53_lab45.configure(text='''Lite''')
        self.fra53_lab45.configure(width=54)

        self.l_procedure = tk.Label(top)
        self.l_procedure.place(relx=0.039, rely=0.781, height=43, width=178)
        self.l_procedure.configure(activebackground="#f9f9f9")
        self.l_procedure.configure(activeforeground="black")
        self.l_procedure.configure(background="#d9d9d9")
        self.l_procedure.configure(disabledforeground="#a3a3a3")
        self.l_procedure.configure(font="-family {Segoe UI} -size 20 -weight bold")
        self.l_procedure.configure(foreground="#000000")
        self.l_procedure.configure(highlightbackground="#d9d9d9")
        self.l_procedure.configure(highlightcolor="black")
        self.l_procedure.configure(text='''PROCEDURE :''')

        self.procedure = tk.Entry(top)
        self.procedure.place(relx=0.039, rely=0.872,height=40, relwidth=0.908)
        self.procedure.configure(background="white")
        self.procedure.configure(disabledforeground="#a3a3a3")
        self.procedure.configure(font="-family {Courier New} -size 14 -weight bold")
        self.procedure.configure(foreground="#000000")
        self.procedure.configure(highlightbackground="#d9d9d9")
        self.procedure.configure(highlightcolor="black")
        self.procedure.configure(insertbackground="black")
        self.procedure.configure(selectbackground="#c4c4c4")
        self.procedure.configure(selectforeground="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.752, rely=0.938, height=21, width=194)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Developed by MOBIS Alabama QC''')

if __name__ == '__main__':
    vp_start_gui()





