#############################################################################
# Generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#  Jul 11, 2019 08:39:35 AM KORST  platform: Windows NT
set vTcl(timestamp) ""


#############################################################################
## vTcl Code to Load User Images see vTcl:save2 in file.tcl

catch {package require Img}

foreach img {

        {{[file join C:/ Users {Mobis Alabama} Desktop {Weight Control} MobisWeightControl Mobis.png]} {user image} user {}}

            } {
# from vTcl:image:dump_create_image_footer
    eval set _file [lindex $img 0]
    vTcl:image:create_new_image\
        $_file [lindex $img 1] [lindex $img 2] [lindex $img 3]
}

if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Segoe UI} -size 23 -weight normal -slant italic -underline 0 -overstrike 0" \
    user \
    vTcl:font13
vTcl:font:add_font \
    "-family {Courier New} -size 18 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font14
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist {_TopLevel _vTclBalloon}
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -borderwidth 1 -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1024x768+483+185
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1024 768
    wm minsize $top 444 70
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "MWC" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab46 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 20 -weight bold} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {PART BARCODE :} 
    vTcl:DefineAlias "$top.lab46" "l_partBarcode" vTcl:WidgetProc "MWC" 1
    label $top.lab48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 20 -weight bold} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {WEIGHT :} 
    vTcl:DefineAlias "$top.lab48" "l_weight" vTcl:WidgetProc "MWC" 1
    entry $top.ent54 \
        -background white -disabledforeground {#a3a3a3} \
        -font {-family {Courier New} -size 20 -weight bold} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black -justify center \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent54" "partBarcode" vTcl:WidgetProc "MWC" 1
    entry $top.ent55 \
        -background white -disabledforeground {#a3a3a3} \
        -font {-family {Courier New} -size 20 -weight bold} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black -justify center \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent55" "weight" vTcl:WidgetProc "MWC" 1
    button $top.but58 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -command abortProcess \
        -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 20 -weight bold} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text ABORT 
    vTcl:DefineAlias "$top.but58" "b_abort" vTcl:WidgetProc "MWC" 1
    label $top.lab43 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 20 -weight bold} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {PART NO :} 
    vTcl:DefineAlias "$top.lab43" "l_partNo" vTcl:WidgetProc "MWC" 1
    label $top.lab49 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 20 -weight bold} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {ALC :} 
    vTcl:DefineAlias "$top.lab49" "l_ALC" vTcl:WidgetProc "MWC" 1
    entry $top.ent53 \
        -background white -disabledforeground {#a3a3a3} \
        -font {-family {Courier New} -size 18 -weight bold} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black -justify center \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent53" "partNo" vTcl:WidgetProc "MWC" 1
    entry $top.ent56 \
        -background white -disabledforeground {#a3a3a3} \
        -font {-family {Courier New} -size 18 -weight bold} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black -justify center \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent56" "ALC" vTcl:WidgetProc "MWC" 1
    label $top.lab63 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 20 -weight bold} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {MODEL :} 
    vTcl:DefineAlias "$top.lab63" "l_readHistory" vTcl:WidgetProc "MWC" 1
    entry $top.ent65 \
        -background white -disabledforeground {#a3a3a3} \
        -font {-family {Courier New} -size 18 -weight bold} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black -justify center \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent65" "model" vTcl:WidgetProc "MWC" 1
    frame $top.fra53 \
        -borderwidth 1 -relief groove -background {#ffffff} -height 95 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 1024 
    vTcl:DefineAlias "$top.fra53" "topFrame" vTcl:WidgetProc "MWC" 1
    set site_3_0 $top.fra53
    button $site_3_0.but54 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -command closeIt -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 28 -weight bold} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text X 
    vTcl:DefineAlias "$site_3_0.but54" "b_closeIt" vTcl:WidgetProc "MWC" 1
    label $site_3_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -image [vTcl:image:get_image [file join C:/ Users {Mobis Alabama} Desktop {Weight Control} MobisWeightControl Mobis.png]] 
    vTcl:DefineAlias "$site_3_0.lab55" "logo" vTcl:WidgetProc "MWC" 1
    label $site_3_0.lab46 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 23 -weight bold} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {WEIGHT CONTROL STATION} 
    vTcl:DefineAlias "$site_3_0.lab46" "l_title" vTcl:WidgetProc "MWC" 1
    label $site_3_0.lab45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 23 -slant italic} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Lite 
    place $site_3_0.but54 \
        -in $site_3_0 -x 900 -y 10 -width 75 -relwidth 0 -height 65 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 50 -y 10 -width 158 -relwidth 0 -height 68 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab46 \
        -in $site_3_0 -x 310 -y 20 -width 424 -relwidth 0 -height 51 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab45 \
        -in $site_3_0 -x 739 -y 50 -width 54 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    label $top.lab60 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 20 -weight bold} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {PROCEDURE :} 
    vTcl:DefineAlias "$top.lab60" "l_procedure" vTcl:WidgetProc "MWC" 1
    entry $top.ent61 \
        -background white -disabledforeground {#a3a3a3} \
        -font {-family {Courier New} -size 14 -weight bold} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent61" "procedure" vTcl:WidgetProc "MWC" 1
    label $top.lab44 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 9 -weight bold} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Developed by MOBIS Alabama QC} 
    vTcl:DefineAlias "$top.lab44" "Label1" vTcl:WidgetProc "MWC" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab46 \
        -in $top -x 40 -y 140 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 40 -y 250 -anchor nw -bordermode ignore 
    place $top.ent54 \
        -in $top -x 280 -y 130 -width 690 -relwidth 0 -height 70 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent55 \
        -in $top -x 280 -y 240 -width 690 -relwidth 0 -height 70 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but58 \
        -in $top -x 570 -y 370 -width 404 -relwidth 0 -height 193 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab43 \
        -in $top -x 40 -y 370 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 40 -y 440 -anchor nw -bordermode ignore 
    place $top.ent53 \
        -in $top -x 190 -y 370 -width 314 -relwidth 0 -height 50 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent56 \
        -in $top -x 190 -y 440 -width 314 -relwidth 0 -height 50 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab63 \
        -in $top -x 40 -y 510 -anchor nw -bordermode ignore 
    place $top.ent65 \
        -in $top -x 190 -y 510 -width 314 -relwidth 0 -height 50 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra53 \
        -in $top -x 0 -y 0 -width 1024 -relwidth 0 -height 95 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab60 \
        -in $top -x 40 -y 600 -anchor nw -bordermode ignore 
    place $top.ent61 \
        -in $top -x 40 -y 670 -width 930 -relwidth 0 -height 40 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab44 \
        -in $top -x 770 -y 720 -width 194 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

